// Header file generated by CMake please don't change it
#ifndef Y_REV_H
#define Y_REV_H
#define YAF_SVN_REV "@YAF_SVN_REV@"
#define LIBPATH "@CMAKE_INSTALL_PREFIX@/@YAF_LIB_DIR@"
#define Y_PLUGINPATH "@CMAKE_INSTALL_PREFIX@/@YAF_PLUGIN_DIR@"
#endif
