#pragma once
// Header file generated by CMake please don't change it

// This preprocessor macro is set by cmake during building in file yaf_version.h.cmake
// For example: cmake -DYAFARAY_CORE_VERSION="v1.2.3"
// the intention is to link the YafaRay Core version to the git information obtained, for example with:
// cmake /yafaray/src/Core -DYAFARAY_CORE_VERSION=`git --git-dir=/yafaray/src/Core/.git --work-tree=/yafaray/src/Core describe --dirty --always --tags --long`

// This file is now also used to store the runtime search path for the plugins, if needed

#ifndef Y_BUILD_H
#define Y_BUILD_H
#define YAFARAY_BUILD_ARCHITECTURE "@YAFARAY_BUILD_ARCHITECTURE@"
#define YAFARAY_BUILD_COMPILER "@YAFARAY_BUILD_COMPILER@"
#define YAFARAY_BUILD_OS "@YAFARAY_BUILD_OS@"
#define YAFARAY_BUILD_PLATFORM "@YAFARAY_BUILD_PLATFORM@"
#endif
