// Header file generated by CMake please don't change it
#ifndef Y_CONFIG_H
#define Y_CONFIG_H
#include "yafray_constants.h"
#include <core_api/color_console.h>
#include <core_api/console_verbosity.h>

#define MIN_RAYDIST 0.00005
#define YAF_SHADOW_BIAS 0.0005

#define Y_INFO yafout.info() << setColor(Green) << "INFO: " << setColor()
#define Y_WARNING yafout.warning() << setColor(Yellow) << "WARNING: " << setColor()
#define Y_ERROR yafout.error() << setColor(Red) << "ERROR: " << setColor()
#define yendl std::endl

__BEGIN_YAFRAY
typedef float CFLOAT;
typedef float GFLOAT;
typedef float PFLOAT;
__END_YAFRAY
#endif

