import sys
Import('append_includes')

#Import('config')
Import('plugin_env')
Import('static_env')
Import('append_lib')

lights_env = plugin_env.Clone()
#append_lib(lights_env, ['EXR'])
append_includes(lights_env, ['EXR'])
append_includes(lights_env, ['PTHREAD'])
append_includes(static_env, ['PTHREAD'])

sunlight=lights_env.SharedLibrary (target='sunlight', source=['sunlight.cc'])
#lights_env.Depends(sunlight,'../yafraycore');
lights_env.Install('${YF_PLUGINPATH}',sunlight)

pointlight=lights_env.SharedLibrary (target='pointlight', source=['pointlight.cc'])
#lights_env.Depends(pointlight,'../yafraycore');
lights_env.Install('${YF_PLUGINPATH}',pointlight)

directional=lights_env.SharedLibrary (target='directional', source=['directional.cc'])
#lights_env.Depends(directional,'../yafraycore');
lights_env.Install('${YF_PLUGINPATH}',directional)

spotlight=lights_env.SharedLibrary (target='spotlight', source=['spotlight.cc'])
lights_env.Install('${YF_PLUGINPATH}',spotlight)

bglight=static_env.Library (target='bglight', source=['bglight.cc'])
#lights_env.Install(config.pluginpath,bglight)

arealight=lights_env.SharedLibrary (target='arealight', source=['arealight.cc', 'meshlight.cc', 'bgportallight.cc'])
#lights_env.Depends(arealight,'../yafraycore');
lights_env.Install('${YF_PLUGINPATH}',arealight)

spherelight=lights_env.SharedLibrary (target='spherelight', source=['spherelight.cc'])
lights_env.Install('${YF_PLUGINPATH}',spherelight)

iesLight=lights_env.SharedLibrary (target='iesLight', source=['iesLight.cc'])
lights_env.Install('${YF_PLUGINPATH}',iesLight)
 
lights_env.Install('${YF_PACKPATH}${YF_PLUGINPATH}',[sunlight,pointlight,directional,spotlight,arealight,spherelight,iesLight])

lights_env.Alias('install_lights','${YF_PLUGINPATH}')
