import sys
Import('append_includes')

Import('plugin_env')
Import('static_env')
Import('append_lib')


cameras_env = plugin_env.Clone();

builtincameras=cameras_env.SharedLibrary (target='builtincameras', source=['builtincameras.cc'])
cameras_env.Install('${YF_PLUGINPATH}',builtincameras)

cameras_env.Install('${YF_PACKPATH}${YF_PLUGINPATH}',[builtincameras])

cameras_env.Alias('install_cameras','${YF_PLUGINPATH}')

