/****************************************************************************
 *
 * 		renderpasses.h: Render Passes functionality
 *      This is part of the yafray package
 *      Copyright (C) 2015  David Bluecame
 *
 *      This library is free software; you can redistribute it and/or
 *      modify it under the terms of the GNU Lesser General Public
 *      License as published by the Free Software Foundation; either
 *      version 2.1 of the License, or (at your option) any later version.
 *
 *      This library is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *      Lesser General Public License for more details.
 *
 *      You should have received a copy of the GNU Lesser General Public
 *      License along with this library; if not, write to the Free Software
 *      Foundation,Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 */

#ifndef Y_RENDERPASSES_H
#define Y_RENDERPASSES_H

#include <yafray_config.h>

#include <iostream>
#include <vector>
#include <string>
#include <map>

__BEGIN_YAFRAY

class color_t;
class colorA_t;


class YAFRAYCORE_EXPORT extPass_t  //Render pass to be exported, for example, to Blender, and mapping to the internal YafaRay render passes generated in different points of the rendering process
{
	public:
		extPass_t(int extPassType, int intPassType);
		bool enabled;		
		int extPassType;
		int tileType;
		int intPassType;
};

class YAFRAYCORE_EXPORT renderPasses_t
{
	public:
		renderPasses_t();
		void generate_pass_maps();	//Generate text strings <-> pass type maps
		void extPass_add(const std::string& sExternalPass, const std::string& sInternalPass);	//Adds a new External Pass associated to an internal pass. Strings are used as parameters and they must match the strings in the maps generated by generate_pass_maps()
        size_t numExtPasses() const;
        int extPassType(size_t pass_seq) const;
		std::string extPassTypeString(size_t pass_seq) const;
        int tileType(size_t pass_seq) const;
        int intPassType(int pass) const;
        
		std::map<int, std::string> extPassMapIntString; //Map int-string for external passes
		std::map<std::string, int> extPassMapStringInt; //Reverse map string-int for external passes
		std::map<int, std::string> intPassMapIntString; //Map int-string for internal passes
		std::map<std::string, int> intPassMapStringInt; //Reverse map string-int for internal passes
        
    protected:
		std::vector<extPass_t> extPasses;		//List of the external Render passes to be exported
};

class YAFRAYCORE_EXPORT colorIntPasses_t  //Internal YafaRay color passes generated in different points of the rendering process
{
	public:
		colorIntPasses_t(renderPasses_t &renderPasses);
		bool enabled(int pass) const;
		void enable_pass(int pass);
		colorA_t& color(int pass);
		colorA_t& operator()(int pass);
		void reset_colors();
		colorA_t init_color(int pass);
		void multiply_colors(float factor);
		colorA_t probe_set(const int& pass, const colorA_t& renderedColor, const bool& condition = true);
		colorA_t probe_set(const int& pass, const colorIntPasses_t& colorPasses, const bool& condition = true);
		colorA_t probe_add(const int& pass, const colorA_t& renderedColor, const bool& condition = true);
		colorA_t probe_add(const int& pass, const colorIntPasses_t& colorPasses, const bool& condition = true);
		colorA_t probe_mult(const int& pass, const colorA_t& renderedColor, const bool& condition = true);
		colorA_t probe_mult(const int& pass, const colorIntPasses_t& colorPasses, const bool& condition = true);
		int get_highest_internal_pass_used() const;
		
		colorIntPasses_t & operator *=(CFLOAT f);
		colorIntPasses_t & operator *=(color_t &a);
		colorIntPasses_t & operator *=(colorA_t &a);
		colorIntPasses_t & operator +=(colorIntPasses_t &a);

		float pass_mask_obj_index;	//Object Index used for masking in/out in the Mask Render Passes
		float pass_mask_mat_index;	//Material Index used for masking in/out in the Mask Render Passes
		bool pass_mask_invert;	//False=mask in, True=mask out
		bool pass_mask_only;	//False=rendered image is masked, True=only the mask is shown without rendered image
    
    protected:
		std::vector <bool> enabledIntPasses;
		std::vector <colorA_t> intPasses;
		renderPasses_t &passDefinitions;
};


enum extPassTypes_t
{
	PASS_EXT_COMBINED				=	0,
	PASS_EXT_Z_DEPTH,
	PASS_EXT_VECTOR,
	PASS_EXT_NORMAL,
	PASS_EXT_UV,
	PASS_EXT_COLOR,
	PASS_EXT_EMIT,
	PASS_EXT_MIST,
	PASS_EXT_DIFFUSE,
	PASS_EXT_SPECULAR,
	PASS_EXT_AO,
	PASS_EXT_ENV,
	PASS_EXT_INDIRECT,
	PASS_EXT_SHADOW,
	PASS_EXT_REFLECT,
	PASS_EXT_REFRACT,
	PASS_EXT_OBJ_INDEX,
	PASS_EXT_MAT_INDEX,
	PASS_EXT_DIFFUSE_DIRECT,
	PASS_EXT_DIFFUSE_INDIRECT,
	PASS_EXT_DIFFUSE_COLOR,
	PASS_EXT_GLOSSY_DIRECT,
	PASS_EXT_GLOSSY_INDIRECT,
	PASS_EXT_GLOSSY_COLOR,
	PASS_EXT_TRANS_DIRECT,
	PASS_EXT_TRANS_INDIRECT,
	PASS_EXT_TRANS_COLOR,
	PASS_EXT_SUBSURFACE_DIRECT,
	PASS_EXT_SUBSURFACE_INDIRECT,
	PASS_EXT_SUBSURFACE_COLOR,
	PASS_EXT_SURFACE_INTEGRATION,
	PASS_EXT_VOLUME_INTEGRATION,
	PASS_EXT_VOLUME_TRANSMITTANCE,
	PASS_EXT_TOTAL_PASSES			//IMPORTANT: KEEP THIS ALWAYS IN THE LAST POSITION
};

enum externalPassTileTypes_t
{
	PASS_EXT_TILE_1_GRAYSCALE		=	 1,
	PASS_EXT_TILE_3_RGB				=	 3,
	PASS_EXT_TILE_4_RGBA			=	 4
};

enum intPassTypes_t
{
	PASS_INT_COMBINED				=	0,
	PASS_INT_Z_DEPTH_NORM,
	PASS_INT_Z_DEPTH_ABS,
	PASS_INT_NORMAL_SMOOTH,
	PASS_INT_NORMAL_GEOM,
	PASS_INT_UV,
	PASS_INT_RADIANCE,
	PASS_INT_EMIT,
	PASS_INT_DIFFUSE,
	PASS_INT_DIFFUSE_NO_SHADOW,
	PASS_INT_AO,
	PASS_INT_AO_CLAY,
	PASS_INT_ENV,
	PASS_INT_MIST,
	PASS_INT_INDIRECT,
	PASS_INT_INDIRECT_ALL,
	PASS_INT_SHADOW,
	PASS_INT_REFLECT_PERFECT,
	PASS_INT_REFRACT_PERFECT,
	PASS_INT_REFLECT_ALL,
	PASS_INT_REFRACT_ALL,
	PASS_INT_OBJ_INDEX_ABS,
	PASS_INT_OBJ_INDEX_NORM,
	PASS_INT_OBJ_INDEX_AUTO,
	PASS_INT_MAT_INDEX_ABS,
	PASS_INT_MAT_INDEX_NORM,
	PASS_INT_MAT_INDEX_AUTO,
	PASS_INT_OBJ_INDEX_MASK,
	PASS_INT_OBJ_INDEX_MASK_SHADOW,
	PASS_INT_OBJ_INDEX_MASK_ALL,
	PASS_INT_MAT_INDEX_MASK,
	PASS_INT_MAT_INDEX_MASK_SHADOW,
	PASS_INT_MAT_INDEX_MASK_ALL,
	PASS_INT_DIFFUSE_INDIRECT,
	PASS_INT_DIFFUSE_COLOR,
	PASS_INT_GLOSSY,
	PASS_INT_GLOSSY_INDIRECT,
	PASS_INT_GLOSSY_COLOR,
	PASS_INT_TRANS,
	PASS_INT_TRANS_INDIRECT,
	PASS_INT_TRANS_COLOR,
	PASS_INT_SUBSURFACE,
	PASS_INT_SUBSURFACE_INDIRECT,
	PASS_INT_SUBSURFACE_COLOR,
	PASS_INT_SURFACE_INTEGRATION,
	PASS_INT_VOLUME_INTEGRATION,
	PASS_INT_VOLUME_TRANSMITTANCE,
	PASS_INT_DEBUG_NU,
	PASS_INT_DEBUG_NV,
	PASS_INT_DEBUG_DPDU,
	PASS_INT_DEBUG_DPDV,
	PASS_INT_DEBUG_DSDU,
	PASS_INT_DEBUG_DSDV,
	PASS_INT_AA_SAMPLES,
	PASS_INT_TOTAL_PASSES			//IMPORTANT: KEEP THIS ALWAYS IN THE LAST POSITION
};


__END_YAFRAY

#endif // Y_RENDERPASSES_H
